version: "3.8"
services:
  productapi:
    image: maltestein/productapi
    # Secret Key muss entweder hier stehen oder im Code im Image
    environment:
      - SECRET_KEY='\xda\xe4\xf0\xe9v\x80\xf1Z\xbdw\xef\x07u\xa1C\xac'
    ports:
      - "5000:5000"
    networks:
      - database-network
    depends_on:
      - mongoproducts
  filmapi:
    image: maltestein/filmapi
    # Secret Key muss entweder hier stehen oder im Code im Image
    environment:
      - SECRET_KEY='\xda\xe4\xf0\xe9v\x80\xf1Z\xbdw\xef\x07u\xa1C\xac'
    ports:
      - "5001:5000"
    networks:
      - database-network
    depends_on:
      - mongomovies
  mongoproducts:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - database-network
    volumes:
      - mongoproducts-config:/data/configdb
      - mongoproducts-data:/data/db
  mongomovies:
    image: mongo:3.6.19-xenial
    command: mongod --port 27018
    ports:
      - "27018:27018"
    networks:
      - database-network
    volumes:
      - mongomovies-config:/data/configdb
      - mongomovies-data:/data/db
  client-produktverwaltung:
    image: maltestein/client
    ports:
      - "8080:8080"
    networks:
      - database-network
networks:
  database-network:
    driver: bridge
volumes:
  mongoproducts-data:
    driver: local
  mongoproducts-config:
    driver: local
  mongomovies-config:
    driver: local
  mongomovies-data:
    driver: local
