version: "3"
services:
  api-server:
    image: ms-produktverwaltung
# Secret Key muss entweder hier stehen oder im Code im Image
#    environment:
#      - SECRET_KEY='\xda\xe4\xf0\xe9v\x80\xf1Z\xbdw\xef\x07u\xa1C\xac'
    ports:
      - "5000:5000"
    networks:
      - database-network
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - database-network
    volumes:
      - mongo-config:/data/configdb
      - mongo-data:/data/db
networks:
  database-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local